[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
crowdfunding_app = "mSgYAxrWrzVCQsiBs8yHVwHjedadMTqbnRmAGv5vPMW"

[programs.localnet]
crowdfunding_app = "HVd9rP3YJZLznrWbb5sjgC5ihtpLXDwBRs1VFv1qV34p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
